// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.appservice.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Identifier resource specific properties. */
@Fluent
public final class IdentifierProperties {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(IdentifierProperties.class);

    /*
     * String representation of the identity.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Get the id property: String representation of the identity.
     *
     * @return the id value.
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id property: String representation of the identity.
     *
     * @param id the id value to set.
     * @return the IdentifierProperties object itself.
     */
    public IdentifierProperties withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
